// ─────────────────────────────────────────────────────────────────────────────
// ARTWORK DATA
//
// To add a new artwork: copy any entry, fill in all fields, add to the array.
// To edit an artwork: find its entry and update the fields below.
//
// Fields you need to fill in:
//   descriptionEn  — English description (shown on top half of detail page)
//   descriptionZh  — Chinese description (shown on bottom half of detail page)
//
// Fields that may need completing (marked with TODO):
//   mediumEn       — English translation of the medium
//   titleZh        — Chinese title
//   dimensions     — if missing from the filename
//   year           — if missing from the filename
// ─────────────────────────────────────────────────────────────────────────────

export const ARTWORKS = [
    {
        // ── Homepage fields (do not remove) ───────────────────────────────
        title:         'All Things on Earth 1',
        medium:        '炭笔、矿物颜料',
        dimensions:    '114 × 78 cm',
        year:          2022,
        aspect:        1.469,
        img:           'assets/images/《All things on earth1》 炭笔、矿物颜料 114×78cm 2022.webp',
        description:   '',   // legacy — kept for homepage overlay
        // ── Detail page fields ────────────────────────────────────────────
        id:            'all-things-on-earth-1',
        titleZh:       '《All things on earth1》',
        mediumEn:      'Charcoal and mineral pigment on paper',
        descriptionEn: '',
        descriptionZh: '',
    },
    {
        title:         'Life',
        medium:        '陶瓷装置',
        dimensions:    '40 × 23 × 41 cm',
        year:          2024,
        aspect:        1.500,
        img:           'assets/images/《life》陶瓷装置 40×23×41cm 2024.webp',
        description:   '',
        id:            'life',
        titleZh:       '《life》',
        mediumEn:      'Ceramic installation',
        descriptionEn: `In the summer of '24 and spring of '25, I immersed myself in Jingdezhen – whether dwelling in nature, visiting ruins or working in the studio, I was constantly accompanied by ducks, dogs and peacocks, and occasionally visited by insects, snakes and toads. Last summer was my first visit to Jingdezhen – a city shrouded in swirling dust and wrapped in clay. I am beyond grateful for having met Mentor Li. In our time together – neither too brief nor too long – he not only taught me Jingdezhen's traditional porcelain craft but also took me on a journey through the city's ancient kiln ruins, clay pits, and working furnaces, showing a deeper, more essential side of the city's heritage. Starlit skies shimmering like the milky way, the thrill of discovering clutches of eggs and witnessing hatchlings emerge, wandering through spring fields, mountain woods, streams and boulders – these are just some of Jingdezhen's indelible fragments.\n\nDue to uneven shrinkage inside the kiln, not leaving a single piece intact. At that moment, I experience a strange sense of calm, as if recognizing the inevitability of fate and impermanence of things.\n\nThe finished, collapsed house seemed like a predestined fable – abandoned, imperfect, and lost. In the eyes of the era and society, it was deemed no longer 'correct' enough, surfeit, no longer needed. In truth, the life of the house resembles human life: from birth to death, stuck within an inescapable cycle of repetition and return.`,
        descriptionZh: `24年夏天和25年的春天，我泡在了景德镇.废墟、自然、工作室的各种鸡鸭狗孔雀、时不时出现的昆虫、小蛇、蟾蜍围绕着我。去年是我头一次到景德镇，第一印象是尘土飞扬，泥土包裹着整个城市.\n\n我很感激遇见李老师，不长不短的时间里不仅教我景德镇传统瓷器的技艺，同时跑了很多古遗址、泥料厂、窑厂等等，带我了解到景德镇更深、更原始的一面.银河般闪烁的星空，发现一窝窝鸡蛋，小鸡出壳的惊喜，在春天的田野、山林、溪水、岩石之间游荡......是景德镇难忘的片段.\n\n陶瓷创作的源起，是基于我2024年3月看到的孤独、废弃房子的情感冲动开始，为完成脑海中的这件作品，我把自己投入到陌生的环境中.尽管花了大力气，房子的框架还是在最后，因为炉内收缩不均衡的原因塌的不成样子，没有一块完好.\n那一刻我却反常的平静，认识到命运的注定和无常.\n\n最后烧制的坍塌的房子像一个注定的寓言，它是被遗弃的、不完美的、失落的，对于时代和社会来说它已经不够"正确"，从而不被需要.房子的一生其实和人的一生很像，从出生到死亡，逃避不了的轮回和反复.`,
    },
    {
        title:         'Spider Web',
        medium:        '布面丙烯',
        dimensions:    '40 × 40 cm',
        year:          2024,
        aspect:        0.997,
        img:           'assets/images/《Spider web》布面丙烯 40×40cm 2024.webp',
        description:   '',
        id:            'spider-web',
        titleZh:       '《蜘蛛网》',
        mediumEn:      'Acrylic on canvas',
        descriptionEn: `Before attending university in Suzhou, I have always lived in Tiantai. As a degree of distance accumulated between myself and my hometown, I began to observe Tiantai's natural features and folk customs from a relatively more detached perspective.\n\nI enjoy exploring Tiantai's wilderness, mountain monasteries, old alleyways and forgotten spaces…\n\nAncient objects and departed ancestors stir up my oldest memories and deepest emotions. Influenced by this habit, I find myself attuning to the subtle tremors of every place I visit, seeking those images that resonate with my inner world.`,
        descriptionZh: `在上大学去苏州之前，我一直生活在天台. 和自己从小生活的地方有一定的距离之后，我开始以一个比较旁观的视角来感受天台的自然风貌和民俗人文\n\n喜欢探索天台的荒野、山寺、老巷和废墟……\n\n古物和故人唤醒我最远的记忆，和最深的情感.这样的习惯也影响我，每到一个地方时，去观察那些微弱的力量，找到与内心有共鸣的画面.`,
    },
    {
        title:         'Victory of Death',
        medium:        '布面丙烯',
        dimensions:    '60 × 50 cm',
        year:          2023,
        aspect:        0.840,
        img:           'assets/images/《Victory of Death》布面丙烯 60×50cm 2023.webp',
        description:   '',
        id:            'victory-of-death',
        titleZh:       '《Victory of Death》',
        mediumEn:      'Acrylic on canvas',
        descriptionEn: `In 《The Triumph of Death》, I alternated the color tones and reconstructed certain elements in order to extract and highlight the main character of the mural - the skeleton armed with a bow and arrows.`,
        descriptionZh: `《死亡的胜利》我用变调、元素重构的手法截取并突出了壁画中的主角——被弓箭武装起来的骷髅`,
    },
    {
        title:         'Virgin of the Rocks',
        medium:        '布面丙烯',
        dimensions:    '30 × 20 cm',
        year:          2023,
        aspect:        1.454,
        img:           'assets/images/《Virgin of the Rocks》 布面丙烯 30×20cm 2023.webp',
        description:   '',
        id:            'virgin-of-the-rocks',
        titleZh:       '《Virgin of the Rocks》',
        mediumEn:      'Acrylic on canvas',
        descriptionEn: `As I painted 《Madonna of the Rocks》, I placed compositional emphasis on the rocks and plants, intentionally reducing religious elements. In this picture, she is simply a young girl moving through nature. Her gaze is gentle yet firm, as if utterly unafraid of anything ahead.`,
        descriptionZh: `《岩间圣母》，在绘画中，我将画面的重点放在岩石、植物上，有意弱化了宗教属性，在画面中她仅是一位穿梭于自然间的少女. 她的目光柔和且坚定，似乎对前方的一切毫无畏惧。`,
    },
    {
        title:         'Courtyard 1',
        medium:        '纸本水彩',
        dimensions:    '131 × 110.5 cm',
        year:          2024,
        aspect:        1.295,
        img:           'assets/images/《庭院系列1》纸本水彩 131×110.5cm 2024.webp',
        description:   '',
        id:            'garden-series-1',
        titleZh:       '《庭院系列1》',
        mediumEn:      'Watercolour on paper',
        descriptionEn: `My Courtyard series was inspired by an encounter with Guangzhou-style enamelware - the dazzling colors of the copper cloisonné colors struck me instantly. The frame of reference for this series is largely concentrated on local traditions and folk culture. Notwithstanding this local focal point, the series also reflects my previous engagement with Western painting – the shadows of classical painting drift through these compositions as symbols and nature intertwine and morph across different temporal spaces.`,
        descriptionZh: `庭院系列的创作契机是在广州接触到广州铜珐琅彩的器物，明艳的色彩一下击中了我. 这个系列中，我的视角更加集中于关注本土以及民俗. 同时，上个阶段对于西方绘画的观看也影响到这组画面的表达. 来自不同时空——古典绘画的影子穿梭其中，符号与自然交织且异化.`,
    },
    {
        title:         'Courtyard 2',
        medium:        '丙烯亚麻布',
        dimensions:    '100 × 80 cm',
        year:          2024,
        aspect:        0.818,
        img:           'assets/images/《庭院系列2》丙烯亚麻布 100×80cm 2024.webp',
        description:   '',
        id:            'garden-series-2',
        titleZh:       '《庭院系列2》',
        mediumEn:      'Acrylic on linen',
        descriptionEn: `My Courtyard series was inspired by an encounter with Guangzhou-style enamelware - the dazzling colors of the copper cloisonné colors struck me instantly. The frame of reference for this series is largely concentrated on local traditions and folk culture. Notwithstanding this local focal point, the series also reflects my previous engagement with Western painting – the shadows of classical painting drift through these compositions as symbols and nature intertwine and morph across different temporal spaces.`,
        descriptionZh: `庭院系列的创作契机是在广州接触到广州铜珐琅彩的器物，明艳的色彩一下击中了我. 这个系列中，我的视角更加集中于关注本土以及民俗. 同时，上个阶段对于西方绘画的观看也影响到这组画面的表达. 来自不同时空——古典绘画的影子穿梭其中，符号与自然交织且异化.`,
    },
    {
        title:         'Courtyard 3',
        medium:        '丙烯亚麻布',
        dimensions:    '120 × 120 cm',
        year:          2025,
        aspect:        1.001,
        img:           'assets/images/《庭院系列3》 丙烯亚麻布 120×120cm 2025.webp',
        description:   '',
        id:            'garden-series-3',
        titleZh:       '《庭院系列3》',
        mediumEn:      'Acrylic on linen',
        descriptionEn: `My Courtyard series was inspired by an encounter with Guangzhou-style enamelware - the dazzling colors of the copper cloisonné colors struck me instantly. The frame of reference for this series is largely concentrated on local traditions and folk culture. Notwithstanding this local focal point, the series also reflects my previous engagement with Western painting – the shadows of classical painting drift through these compositions as symbols and nature intertwine and morph across different temporal spaces.`,
        descriptionZh: `庭院系列的创作契机是在广州接触到广州铜珐琅彩的器物，明艳的色彩一下击中了我. 这个系列中，我的视角更加集中于关注本土以及民俗. 同时，上个阶段对于西方绘画的观看也影响到这组画面的表达. 来自不同时空——古典绘画的影子穿梭其中，符号与自然交织且异化.`,
    },
    {
        title:         'Courtyard 4',
        medium:        '丙烯亚麻布',
        dimensions:    '110.5 × 79.5 cm',
        year:          2025,
        aspect:        0.749,
        img:           'assets/images/庭院系列 4 2025 110.5 x 79.5.webp',
        description:   '',
        id:            'garden-series-4',
        titleZh:       '庭院系列 4',
        mediumEn:      'Acrylic on linen',
        descriptionEn: `My Courtyard series was inspired by an encounter with Guangzhou-style enamelware - the dazzling colors of the copper cloisonné colors struck me instantly. The frame of reference for this series is largely concentrated on local traditions and folk culture. Notwithstanding this local focal point, the series also reflects my previous engagement with Western painting – the shadows of classical painting drift through these compositions as symbols and nature intertwine and morph across different temporal spaces.`,
        descriptionZh: `庭院系列的创作契机是在广州接触到广州铜珐琅彩的器物，明艳的色彩一下击中了我. 这个系列中，我的视角更加集中于关注本土以及民俗. 同时，上个阶段对于西方绘画的观看也影响到这组画面的表达. 来自不同时空——古典绘画的影子穿梭其中，符号与自然交织且异化.`,
    },
    {
        title:         'Water Coconut',
        medium:        '布面丙烯',
        dimensions:    '40 × 30 cm',
        year:          2024,
        aspect:        1.245,
        img:           'assets/images/《水椰》 布面丙烯 40×30cm 2024.webp',
        description:   '',
        id:            'water-coconut',
        titleZh:       '《水椰》',
        mediumEn:      'Acrylic on canvas',
        descriptionEn: `Before attending university in Suzhou, I have always lived in Tiantai. As a degree of distance accumulated between myself and my hometown, I began to observe Tiantai's natural features and folk customs from a relatively more detached perspective.\n\nI enjoy exploring Tiantai's wilderness, mountain monasteries, old alleyways and forgotten spaces…\n\nAncient objects and departed ancestors stir up my oldest memories and deepest emotions. Influenced by this habit, I find myself attuning to the subtle tremors of every place I visit, seeking those images that resonate with my inner world.`,
        descriptionZh: `在上大学去苏州之前，我一直生活在天台. 和自己从小生活的地方有一定的距离之后，我开始以一个比较旁观的视角来感受天台的自然风貌和民俗人文\n\n喜欢探索天台的荒野、山寺、老巷和废墟……\n\n古物和故人唤醒我最远的记忆，和最深的情感.这样的习惯也影响我，每到一个地方时，去观察那些微弱的力量，找到与内心有共鸣的画面.`,
    },
    {
        title:         'Wanderer',
        medium:        '纸本水彩',
        dimensions:    '53 × 36.8 cm',
        year:          2024,
        aspect:        1.460,
        img:           'assets/images/《游荡者》纸本水彩 53×36.8cm 2024.webp',
        description:   '',
        id:            'wanderer',
        titleZh:       '《游荡者》',
        mediumEn:      'Watercolour on paper',
        descriptionEn: `Before attending university in Suzhou, I have always lived in Tiantai. As a degree of distance accumulated between myself and my hometown, I began to observe Tiantai's natural features and folk customs from a relatively more detached perspective.\n\nI enjoy exploring Tiantai's wilderness, mountain monasteries, old alleyways and forgotten spaces…\n\nAncient objects and departed ancestors stir up my oldest memories and deepest emotions. Influenced by this habit, I find myself attuning to the subtle tremors of every place I visit, seeking those images that resonate with my inner world.`,
        descriptionZh: `在上大学去苏州之前，我一直生活在天台. 和自己从小生活的地方有一定的距离之后，我开始以一个比较旁观的视角来感受天台的自然风貌和民俗人文\n\n喜欢探索天台的荒野、山寺、老巷和废墟……\n\n古物和故人唤醒我最远的记忆，和最深的情感.这样的习惯也影响我，每到一个地方时，去观察那些微弱的力量，找到与内心有共鸣的画面.`,
    },
    {
        title:         'A Corner of the County Seat',
        medium:        '',   // TODO: fill in medium
        dimensions:    '60 × 30 cm',
        year:          2025,
        aspect:        0.486,
        img:           'assets/images/县城一角 60×30cm 2025.webp',
        description:   '',
        id:            'corner-of-county-seat',
        titleZh:       '县城一角',
        mediumEn:      '',   // TODO: fill in medium (English)
        descriptionEn: `Before attending university in Suzhou, I have always lived in Tiantai. As a degree of distance accumulated between myself and my hometown, I began to observe Tiantai's natural features and folk customs from a relatively more detached perspective.\n\nI enjoy exploring Tiantai's wilderness, mountain monasteries, old alleyways and forgotten spaces…\n\nAncient objects and departed ancestors stir up my oldest memories and deepest emotions. Influenced by this habit, I find myself attuning to the subtle tremors of every place I visit, seeking those images that resonate with my inner world.`,
        descriptionZh: `在上大学去苏州之前，我一直生活在天台. 和自己从小生活的地方有一定的距离之后，我开始以一个比较旁观的视角来感受天台的自然风貌和民俗人文\n\n喜欢探索天台的荒野、山寺、老巷和废墟……\n\n古物和故人唤醒我最远的记忆，和最深的情感.这样的习惯也影响我，每到一个地方时，去观察那些微弱的力量，找到与内心有共鸣的画面.`,
    },
    {
        title:         'Taihu Rocks',
        medium:        '纸本水彩',
        dimensions:    '76.6 × 57.3 cm',
        year:          2023,
        aspect:        1.418,
        img:           'assets/images/太湖石 纸本水彩 76.6×57.3cm 2023.webp',
        description:   '',
        id:            'taihu-rocks',
        titleZh:       '太湖石',
        mediumEn:      'Watercolour on paper',
        descriptionEn: `The Taihu stones brought back to me memories of my life in Suzhou, so I started by depicting them.\nBlood vessels, fingers, the heart, they flow among all the natural things. The chain symbolizes the cycle of life.\n\nThe creative process requires a balance between control and chance, involving uncertain experiments from which traces emerge naturally and inevitably. I enjoy this state of exploring in the unknown.`,
        descriptionZh: `太湖石勾起我在苏州生活的记忆，于是我决定从描绘它开始. 血管、手指、心脏在自然万物间流动，锁链象征着生命的轮回\n\n创作过程需要控制与偶然的平衡，不确定的实验，使痕迹自然而然又命中注定的出现，我很享受未知中探索的状态.`,
    },
    {
        title:         'The Lonely Boat',
        medium:        '丙烯亚麻布',
        dimensions:    '80 × 60 cm',
        year:          2025,
        aspect:        0.758,
        img:           'assets/images/孤舟 丙烯亚麻布 80×60cm 2025.webp',
        description:   '',
        id:            'solitary-boat',
        titleZh:       '孤舟',
        mediumEn:      'Acrylic on linen',
        descriptionEn: `Before attending university in Suzhou, I have always lived in Tiantai. As a degree of distance accumulated between myself and my hometown, I began to observe Tiantai's natural features and folk customs from a relatively more detached perspective.\n\nI enjoy exploring Tiantai's wilderness, mountain monasteries, old alleyways and forgotten spaces…\n\nAncient objects and departed ancestors stir up my oldest memories and deepest emotions. Influenced by this habit, I find myself attuning to the subtle tremors of every place I visit, seeking those images that resonate with my inner world.`,
        descriptionZh: `在上大学去苏州之前，我一直生活在天台. 和自己从小生活的地方有一定的距离之后，我开始以一个比较旁观的视角来感受天台的自然风貌和民俗人文\n\n喜欢探索天台的荒野、山寺、老巷和废墟……\n\n古物和故人唤醒我最远的记忆，和最深的情感.这样的习惯也影响我，每到一个地方时，去观察那些微弱的力量，找到与内心有共鸣的画面.`,
    },
    {
        title:         'The Abandoned House',
        medium:        '丙烯亚麻布',
        dimensions:    '80 × 60 cm',
        year:          2024,
        aspect:        0.759,
        img:           'assets/images/废弃的房子 丙烯亚麻布 80×60cm 2024.webp',
        description:   '',
        id:            'abandoned-house',
        titleZh:       '废弃的房子',
        mediumEn:      'Acrylic on linen',
        descriptionEn: `Before attending university in Suzhou, I have always lived in Tiantai. As a degree of distance accumulated between myself and my hometown, I began to observe Tiantai's natural features and folk customs from a relatively more detached perspective.\n\nI enjoy exploring Tiantai's wilderness, mountain monasteries, old alleyways and forgotten spaces…\n\nAncient objects and departed ancestors stir up my oldest memories and deepest emotions. Influenced by this habit, I find myself attuning to the subtle tremors of every place I visit, seeking those images that resonate with my inner world.`,
        descriptionZh: `在上大学去苏州之前，我一直生活在天台. 和自己从小生活的地方有一定的距离之后，我开始以一个比较旁观的视角来感受天台的自然风貌和民俗人文\n\n喜欢探索天台的荒野、山寺、老巷和废墟……\n\n古物和故人唤醒我最远的记忆，和最深的情感.这样的习惯也影响我，每到一个地方时，去观察那些微弱的力量，找到与内心有共鸣的画面.`,
    },
    {
        title:         'Dead Trees',
        medium:        '丙烯亚麻布',
        dimensions:    '120 × 80 cm',
        year:          2025,
        aspect:        1.502,
        img:           'assets/images/枯树 丙烯亚麻布 120×80cm 2025.webp',
        description:   '',
        id:            'withered-tree',
        titleZh:       '枯树',
        mediumEn:      'Acrylic on linen',
        descriptionEn: `Before attending university in Suzhou, I have always lived in Tiantai. As a degree of distance accumulated between myself and my hometown, I began to observe Tiantai's natural features and folk customs from a relatively more detached perspective.\n\nI enjoy exploring Tiantai's wilderness, mountain monasteries, old alleyways and forgotten spaces…\n\nAncient objects and departed ancestors stir up my oldest memories and deepest emotions. Influenced by this habit, I find myself attuning to the subtle tremors of every place I visit, seeking those images that resonate with my inner world.`,
        descriptionZh: `在上大学去苏州之前，我一直生活在天台. 和自己从小生活的地方有一定的距离之后，我开始以一个比较旁观的视角来感受天台的自然风貌和民俗人文\n\n喜欢探索天台的荒野、山寺、老巷和废墟……\n\n古物和故人唤醒我最远的记忆，和最深的情感.这样的习惯也影响我，每到一个地方时，去观察那些微弱的力量，找到与内心有共鸣的画面.`,
    },
    {
        title:         '瓷板画 1',
        medium:        '瓷板画',
        dimensions:    '',         // TODO: fill in dimensions
        year:          2025,       // TODO: fill in year
        aspect:        1.500,
        img:           'assets/images/瓷板画1.webp',
        description:   '',
        id:            'porcelain-painting-1',
        titleZh:       '瓷板画1',
        mediumEn:      'Porcelain painting',
        descriptionEn: `This collection of works was born from the soil and smoky warmth of Jingdezhen in spring.\nThe spark of inspiration hides in those fleeting fragments of light and shadow...\nIt is the flowering tree at the studio door, whose fruit — if it will ever come — remains a quiet mystery;\nIt is the temperature woven between the warm afternoon sun of early spring and the cold night wind that has not yet fully retreated;\nIt is the stillness felt riding an electric scooter through fields ablaze with rapeseed blossoms, watching farmers at their work, as chimney smoke and the evening glow rise together into the sky;\nIt is the joy of shared adventure — climbing the hill to dig for bamboo shoots, gathering curious pieces of driftwood and moss-covered stones along the stream, and waiting together, breathless with delight, for tiny chicks to crack their way into the world.`,
        descriptionZh: `这组作品，诞生于景德镇春天的泥土与烟火气。\n灵光藏在那些细碎的光影里……\n是工作室门口那棵不知能否结出桃子的花树；\n是初春午后的暖阳与夜里尚未散尽的冷风交织出的温度；\n是骑着电瓶车，穿过开满油菜花的田野，看农人劳作，炊烟与晚霞一同升起的平静感受；\n是一起冒险；上山挖笋、捡拾溪边奇特的木头与长满青苔的石头、一起等待小鸡破壳出生的欣喜.`,
    },
    {
        title:         '瓷板画 2',
        medium:        '瓷板画',
        dimensions:    '',
        year:          2025,
        aspect:        1.500,
        img:           'assets/images/瓷板画2.webp',
        description:   '',
        id:            'porcelain-painting-2',
        titleZh:       '瓷板画2',
        mediumEn:      'Porcelain painting',
        descriptionEn: `This collection of works was born from the soil and smoky warmth of Jingdezhen in spring.\nThe spark of inspiration hides in those fleeting fragments of light and shadow...\nIt is the flowering tree at the studio door, whose fruit — if it will ever come — remains a quiet mystery;\nIt is the temperature woven between the warm afternoon sun of early spring and the cold night wind that has not yet fully retreated;\nIt is the stillness felt riding an electric scooter through fields ablaze with rapeseed blossoms, watching farmers at their work, as chimney smoke and the evening glow rise together into the sky;\nIt is the joy of shared adventure — climbing the hill to dig for bamboo shoots, gathering curious pieces of driftwood and moss-covered stones along the stream, and waiting together, breathless with delight, for tiny chicks to crack their way into the world.`,
        descriptionZh: `这组作品，诞生于景德镇春天的泥土与烟火气。\n灵光藏在那些细碎的光影里……\n是工作室门口那棵不知能否结出桃子的花树；\n是初春午后的暖阳与夜里尚未散尽的冷风交织出的温度；\n是骑着电瓶车，穿过开满油菜花的田野，看农人劳作，炊烟与晚霞一同升起的平静感受；\n是一起冒险；上山挖笋、捡拾溪边奇特的木头与长满青苔的石头、一起等待小鸡破壳出生的欣喜.`,
    },
    {
        title:         '水面',
        medium:        '瓷板画',
        dimensions:    '',         // TODO: fill in dimensions
        year:          2025,       // TODO: fill in year
        aspect:        1.500,
        img:           'assets/images/水面1.webp',
        description:   '',
        id:            'water-surface',
        titleZh:       '水面',
        mediumEn:      'Porcelain painting',
        descriptionEn: `This collection of works was born from the soil and smoky warmth of Jingdezhen in spring.\nThe spark of inspiration hides in those fleeting fragments of light and shadow...\nIt is the flowering tree at the studio door, whose fruit — if it will ever come — remains a quiet mystery;\nIt is the temperature woven between the warm afternoon sun of early spring and the cold night wind that has not yet fully retreated;\nIt is the stillness felt riding an electric scooter through fields ablaze with rapeseed blossoms, watching farmers at their work, as chimney smoke and the evening glow rise together into the sky;\nIt is the joy of shared adventure — climbing the hill to dig for bamboo shoots, gathering curious pieces of driftwood and moss-covered stones along the stream, and waiting together, breathless with delight, for tiny chicks to crack their way into the world.`,
        descriptionZh: `这组作品，诞生于景德镇春天的泥土与烟火气。\n灵光藏在那些细碎的光影里……\n是工作室门口那棵不知能否结出桃子的花树；\n是初春午后的暖阳与夜里尚未散尽的冷风交织出的温度；\n是骑着电瓶车，穿过开满油菜花的田野，看农人劳作，炊烟与晚霞一同升起的平静感受；\n是一起冒险；上山挖笋、捡拾溪边奇特的木头与长满青苔的石头、一起等待小鸡破壳出生的欣喜.`,
    },
    {
        title:         '瓷板画 3',
        medium:        '瓷板画',
        dimensions:    '',         // TODO: fill in dimensions
        year:          2025,       // TODO: fill in year
        aspect:        1.500,
        img:           'assets/images/瓷板画3.webp',
        description:   '',
        id:            'porcelain-painting-3',
        titleZh:       '瓷板画3',
        mediumEn:      'Porcelain painting',
        descriptionEn: `This collection of works was born from the soil and smoky warmth of Jingdezhen in spring.\nThe spark of inspiration hides in those fleeting fragments of light and shadow...\nIt is the flowering tree at the studio door, whose fruit — if it will ever come — remains a quiet mystery;\nIt is the temperature woven between the warm afternoon sun of early spring and the cold night wind that has not yet fully retreated;\nIt is the stillness felt riding an electric scooter through fields ablaze with rapeseed blossoms, watching farmers at their work, as chimney smoke and the evening glow rise together into the sky;\nIt is the joy of shared adventure — climbing the hill to dig for bamboo shoots, gathering curious pieces of driftwood and moss-covered stones along the stream, and waiting together, breathless with delight, for tiny chicks to crack their way into the world.`,
        descriptionZh: `这组作品，诞生于景德镇春天的泥土与烟火气。\n灵光藏在那些细碎的光影里……\n是工作室门口那棵不知能否结出桃子的花树；\n是初春午后的暖阳与夜里尚未散尽的冷风交织出的温度；\n是骑着电瓶车，穿过开满油菜花的田野，看农人劳作，炊烟与晚霞一同升起的平静感受；\n是一起冒险；上山挖笋、捡拾溪边奇特的木头与长满青苔的石头、一起等待小鸡破壳出生的欣喜.`,
    },
];
